# config/config.yaml

QDRANT_COLLECTION_NAME: "medical_documents_new"
QDRANT_PATH: "./qdrant_data"

EMBEDDING_MODEL_NAME: "BAAI/bge-large-en-v1.5"
LLM_MODEL_NAME : "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

PDF_DIR: "./data"
CHUNK_SIZE: 512
CHUNK_OVERLAP: 50